#!/bin/sh

project_name='Change-of-support'

has_session() {
    tmux has-session -t $project_name 2>/dev/null
}

if has_session; then
    tmux attach-session -t $project_name -d
else
    bigproj="$HOME/documents/projects"
    proj="$bigproj/change-of-support"
    tmux new-session -d -c $proj -s $project_name

    # window: notes
    tmux rename-window "notes"
    tmux send-keys "nvim README.md" C-m

    # window: scripts
    tmux new-window -c "$proj/scripts"
    tmux rename-window "scripts"
    tmux send-keys 'nvim' C-m

    # window: src
    tmux new-window -c "$proj/scripts"
    tmux rename-window "src"
    tmux send-keys 'nvim' C-m

    # window: paper
    tmux new-window -c "$proj/writing/paper"
    tmux rename-window "paper"
    tmux send-keys 'nvim' C-m

    # focus on window:
    tmux select-window -t "scripts"
    tmux attach-session -d
fi
