#!/bin/sh

project_name='ChangeOfSupport'

if ! mountpoint -q /home/chaconmo/docserver; then
    sshfs -o default_permissions,uid=1000,gid=998 geohealth1:/home/chaconea/documents ~/docserver
fi

has_session() {
    tmux has-session -t $project_name 2>/dev/null
}

if has_session; then
    tmux attach-session -t $project_name -d
else
    proj="$HOME/docserver/repositories/changeofsupport"
    tmux new-session -d -c $proj -s $project_name

    # window: notes
    tmux rename-window "notes"
    tmux send-keys "nvim README.md" C-m

    # window: source
    tmux new-window -c "$proj/src"
    tmux rename-window "src"
    tmux send-keys 'lf' C-m

    # window: source
    tmux new-window -c "$proj/test"
    tmux rename-window "test"
    tmux send-keys 'lf' C-m

    # window: documentation
    tmux new-window -c "$proj/docs"
    tmux rename-window "docs"
    tmux send-keys 'lf' C-m

    # focus on window:
    tmux select-window -t "src"
    tmux attach-session -d
fi
