#!/bin/sh

project_name='ChangeOfSupport'

has_session() {
    tmux has-session -t $project_name 2>/dev/null
}

if has_session; then
    tmux attach-session -t $project_name -d
else
    proj="$HOME/documents/repositories/changeofsupport"
    tmux new-session -d -c $proj -s $project_name

    # window: notes
    tmux rename-window "notes"
    tmux send-keys "nvim README.md" C-m

    # window: source
    tmux new-window -c "$proj/src"
    tmux rename-window "src"
    tmux send-keys 'nvim' C-m

    # window: literate
    tmux new-window -c "$proj/literate"
    tmux rename-window "literate"
    tmux send-keys 'nvim' C-m

    # window: documentation
    tmux new-window -c "$proj/docs"
    tmux rename-window "docs"
    tmux send-keys 'nvim' C-m

    # focus on window:
    tmux select-window -t "src"
    tmux attach-session -d
fi
