#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# custom settings (dpi, colors)

xrdb ~/.config/x11/xresources
xrdb -merge ~/.config/x11/xdpi-$(cat /etc/hostname)

# dwm

xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0041.jpg
dwmblocks &
exec dwm

# xcompmgr &
### nohup "davmail ~/.config/davmail/davmail.properties &" > plophub.out
# nohup davmail ~/.config/davmail/davmail.properties > ~/.cache/nohup/nohup.out &
### nohup davmail davmail.properties &
