#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# custom settings like dpi and colors (optionally depending of the machine)

xrdb ~/.config/x11/xresources
xrdb -merge ~/.config/x11/xdpi-$(cat /etc/hostname)

# window manafer set up (dwm)

xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0046.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0041.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0305.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0187.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0074.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0085.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0107.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0006.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0016.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0031.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/dt/0044.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/flickr/49414742368_f28c5ee506_k.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/flickr/44656855314_3fa10aad6d_k.jpg
# xwallpaper --zoom /home/chaconmo/pictures/wallpapers/flickr/31505404108_5aeee861b7_k.jpg
dwmblocks &
exec dwm
# xcompmgr &

# davmail settings
### nohup "davmail ~/.config/davmail/davmail.properties &" > plophub.out
# nohup davmail ~/.config/davmail/davmail.properties > ~/.cache/nohup/nohup.out &
### nohup davmail davmail.properties &
